version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/DeskFeed Backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/DeskFeed Agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/DeskFeed Controller"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/DeskFeed Mobile"
    schedule:
      interval: "weekly"
